<?php

return [
    'name' => 'Jiwa Cyber Network',
    'tagline' => 'Premium IT Network Infrastructure',
    'description' => 'Jiwa Cyber Network delivers enterprise-grade network installation, WiFi optimization, structured cabling, and infrastructure maintenance to ensure stable, secure, and high-performance connectivity for businesses across Bali.',
    
    'contact' => [
        'email' => 'hello@jiwacyber.net',
        'phone' => '+62 812 3456 7890',
        'whatsapp' => '6281234567890',
        'address' => 'Jl. Teknologi Canggih No. 42, Denpasar, Bali, Indonesia',
        'maps_url' => 'https://maps.google.com/?q=Denpasar+Bali',
        'business_hours' => 'Mon - Sat: 08:00 - 17:00 WITA',
        'emergency_hours' => '24/7 Available',
    ],
    
    'social' => [
        'linkedin' => 'https://linkedin.com/company/jiwacybernetwork',
        'instagram' => 'https://instagram.com/jiwacybernetwork',
        'twitter' => 'https://twitter.com/jiwacyber',
        'facebook' => 'https://facebook.com/jiwacyber',
    ],

    'stats' => [
        'years_experience' => 10,
        'projects_completed' => 250,
        'happy_clients' => 150,
        'response_time' => '< 1 Hour',
    ],

    'service_areas' => [
        'Denpasar',
        'Badung',
        'Gianyar',
        'Tabanan',
        'Seluruh Bali (Entire Bali)',
    ],

    'tech_partners' => [
        ['name' => 'Ruijie', 'logo' => 'https://www.aikomtech.com/wp-content/uploads/2024/04/logo-ruijie-768x230.png'],
        ['name' => 'MikroTik', 'logo' => 'https://icon2.cleanpng.com/20180624/wlk/aazkuic18.webp'],
        ['name' => 'Ubiquiti', 'logo' => 'https://cdn.imgbin.com/13/16/25/imgbin-ubiquiti-networks-computer-network-wireless-wi-fi-unifi-others-SP87CYMXF5eHn6ei42u2CMnwa.jpg'],
        ['name' => 'TP-Link', 'logo' => 'https://spng.pngfind.com/pngs/s/235-2353698_tp-link-logo-graphic-design-hd-png-download.png'],
        ['name' => 'Belden', 'logo' => 'https://www.liblogo.com/img-logo/be4988b606-belden-logo-belden-logo-download-vector.png'],
        ['name' => 'Hikvision', 'logo' => 'https://banner2.cleanpng.com/20180816/uks/08c3b961da49666776243dde112517e7.webp'],
        ['name' => 'Starlink', 'logo' => 'https://w7.pngwing.com/pngs/142/745/png-transparent-starlink-logo.png'],
    ],

    'services' => [
        [
            'id' => 'network-installation',
            'icon' => 'network',
            'title_id' => 'Instalasi Jaringan',
            'title_en' => 'Network Installation',
            'desc_id' => 'Instalasi profesional infrastruktur jaringan tingkat enterprise.',
            'desc_en' => 'Professional installation of enterprise-grade network infrastructure.',
            'benefits_id' => ['Instalasi Router', 'Instalasi Switch', 'Penyebaran Access Point', 'Instalasi Firewall', 'Instalasi Rak Server', 'Wireless Point-to-Point'],
            'benefits_en' => ['Router Installation', 'Switch Installation', 'Access Point Deployment', 'Firewall Installation', 'Server Rack Installation', 'Wireless Point-to-Point'],
        ],
        [
            'id' => 'network-configuration',
            'icon' => 'activity',
            'title_id' => 'Konfigurasi Jaringan',
            'title_en' => 'Network Configuration',
            'desc_id' => 'Konfigurasi jaringan yang aman dan optimal.',
            'desc_en' => 'Secure and optimized network configuration.',
            'benefits_id' => ['VLAN', 'VPN', 'DHCP', 'DNS', 'Load Balancing', 'Failover', 'QoS', 'Aturan Firewall'],
            'benefits_en' => ['VLAN', 'VPN', 'DHCP', 'DNS', 'Load Balancing', 'Failover', 'QoS', 'Firewall Rules'],
        ],
        [
            'id' => 'lan-fiber-optic',
            'icon' => 'cable',
            'title_id' => 'LAN & Fiber Optik',
            'title_en' => 'LAN & Fiber Optic',
            'desc_id' => 'Sistem pengkabelan terstruktur dan penyebaran fiber optik yang andal.',
            'desc_en' => 'Reliable structured cabling and fiber optic deployment.',
            'benefits_id' => ['Pengkabelan LAN', 'Instalasi Fiber Optik', 'Fusion Splicing', 'Pengujian OTDR', 'Patch Panel', 'Manajemen Kabel'],
            'benefits_en' => ['LAN Cabling', 'Fiber Optic Installation', 'Fusion Splicing', 'OTDR Testing', 'Patch Panel', 'Cable Management'],
        ],
        [
            'id' => 'wifi-solution',
            'icon' => 'wifi',
            'title_id' => 'Solusi WiFi',
            'title_en' => 'WiFi Solution',
            'desc_id' => 'Optimalisasi cakupan nirkabel secara menyeluruh.',
            'desc_en' => 'Complete wireless coverage optimization.',
            'benefits_id' => ['Survei WiFi', 'Analisis Heatmap', 'Optimalisasi Cakupan', 'Konfigurasi Roaming', 'Penyebaran Access Point'],
            'benefits_en' => ['WiFi Survey', 'Heatmap Analysis', 'Coverage Optimization', 'Roaming Configuration', 'Access Point Deployment'],
        ],
        [
            'id' => 'cctv-solution',
            'icon' => 'shield',
            'title_id' => 'Solusi CCTV',
            'title_en' => 'CCTV Solution',
            'desc_id' => 'Instalasi CCTV profesional dan sistem pemantauan.',
            'desc_en' => 'Professional CCTV installation and monitoring systems.',
            'benefits_id' => ['Instalasi CCTV', 'Kamera IP', 'DVR', 'NVR', 'Pemantauan Jarak Jauh', 'Pengaturan Penyimpanan'],
            'benefits_en' => ['CCTV Installation', 'IP Camera', 'DVR', 'NVR', 'Remote Monitoring', 'Storage Setup'],
        ],
        [
            'id' => 'starlink-services',
            'icon' => 'network',
            'title_id' => 'Layanan Starlink',
            'title_en' => 'Starlink Services',
            'desc_id' => 'Penyebaran dan integrasi Starlink profesional.',
            'desc_en' => 'Professional Starlink deployment and integration.',
            'benefits_id' => ['Survei Lokasi', 'Instalasi', 'Relokasi', 'Integrasi Jaringan', 'Pemeliharaan'],
            'benefits_en' => ['Site Survey', 'Installation', 'Relocation', 'Network Integration', 'Maintenance'],
        ],
        [
            'id' => 'network-troubleshooting',
            'icon' => 'activity',
            'title_id' => 'Pemecahan Masalah Jaringan',
            'title_en' => 'Network Troubleshooting',
            'desc_id' => 'Diagnosis cepat dan perbaikan masalah jaringan.',
            'desc_en' => 'Rapid diagnosis and repair of network issues.',
            'benefits_id' => ['Internet Lambat', 'Packet Loss', 'Masalah WiFi', 'Masalah Router', 'Masalah Switch', 'Pemecahan Masalah Firewall'],
            'benefits_en' => ['Slow Internet', 'Packet Loss', 'WiFi Issues', 'Router Problems', 'Switch Problems', 'Firewall Troubleshooting'],
        ],
        [
            'id' => 'maintenance-contract',
            'icon' => 'shield',
            'title_id' => 'Kontrak Pemeliharaan',
            'title_en' => 'Maintenance Contract',
            'desc_id' => 'Pemeliharaan preventif untuk keandalan jaringan jangka panjang.',
            'desc_en' => 'Preventive maintenance for long-term network reliability.',
            'benefits_id' => ['Inspeksi Rutin', 'Pembaruan Firmware', 'Cadangan Konfigurasi', 'Pemantauan', 'Pembersihan Peralatan', 'Laporan Bulanan'],
            'benefits_en' => ['Routine Inspection', 'Firmware Updates', 'Configuration Backup', 'Monitoring', 'Equipment Cleaning', 'Monthly Reports'],
        ],
        [
            'id' => 'network-audit',
            'icon' => 'server',
            'title_id' => 'Audit Jaringan',
            'title_en' => 'Network Audit',
            'desc_id' => 'Penilaian dan optimalisasi infrastruktur profesional.',
            'desc_en' => 'Professional infrastructure assessment and optimization.',
            'benefits_id' => ['Audit Infrastruktur', 'Analisis Performa', 'Penilaian Keamanan', 'Rekomendasi Peningkatan'],
            'benefits_en' => ['Infrastructure Audit', 'Performance Analysis', 'Security Assessment', 'Upgrade Recommendations'],
        ],
        [
            'id' => 'it-consulting',
            'icon' => 'network',
            'title_id' => 'Konsultasi TI',
            'title_en' => 'IT Consulting',
            'desc_id' => 'Perencanaan strategis untuk infrastruktur bisnis yang dapat diskalakan.',
            'desc_en' => 'Strategic planning for scalable business infrastructure.',
            'benefits_id' => ['Desain Topologi', 'Perencanaan Infrastruktur', 'Perencanaan Anggaran', 'Rekomendasi Keamanan', 'Perencanaan Peningkatan'],
            'benefits_en' => ['Topology Design', 'Infrastructure Planning', 'Budget Planning', 'Security Recommendations', 'Upgrade Planning'],
        ]
    ],

    'process' => [
        [
            'step' => 1,
            'title_id' => 'Survei & Konsultasi',
            'title_en' => 'Survey & Consultation',
            'desc_id' => 'Kami menganalisis lokasi dan memahami kebutuhan spesifik infrastruktur bisnis Anda.',
            'desc_en' => 'We analyze the location and understand the specific needs of your business infrastructure.',
        ],
        [
            'step' => 2,
            'title_id' => 'Desain Topologi',
            'title_en' => 'Topology Design',
            'desc_id' => 'Merancang cetak biru arsitektur jaringan yang optimal, efisien, dan siap dikembangkan.',
            'desc_en' => 'Designing an optimal, efficient, and scalable network architecture blueprint.',
        ],
        [
            'step' => 3,
            'title_id' => 'Instalasi Sistem',
            'title_en' => 'System Installation',
            'desc_id' => 'Eksekusi profesional oleh teknisi berpengalaman dengan standar kerapian industri tertinggi.',
            'desc_en' => 'Professional execution by experienced technicians with the highest industry standards of neatness.',
        ],
        [
            'step' => 4,
            'title_id' => 'Testing & Dukungan',
            'title_en' => 'Testing & Support',
            'desc_id' => 'Pengujian beban jaringan menyeluruh dan garansi layanan berkelanjutan paska pemasangan.',
            'desc_en' => 'Comprehensive network load testing and ongoing post-installation service warranty.',
        ]
    ],

    'portfolio' => [
        [
            'id' => 'luxury-villa-canggu',
            'image' => 'portfolio/villa-canggu.jpg',
            'gallery' => ['portfolio/villa-1.jpg', 'portfolio/villa-2.jpg'],
            'before_after' => ['before' => 'portfolio/villa-before.jpg', 'after' => 'portfolio/villa-after.jpg'],
            'title_en' => 'Luxury Villa Network Coverage',
            'title_id' => 'Cakupan Jaringan Vila Mewah',
            'category_en' => 'Villa',
            'category_id' => 'Vila',
            'client_en' => 'Private Villa, Canggu',
            'client_id' => 'Vila Pribadi, Canggu',
            'problem_en' => 'Dead zones and weak WiFi signals in a large villa complex.',
            'problem_id' => 'Zona mati dan sinyal WiFi lemah di kompleks vila yang luas.',
            'solution_en' => 'Implemented seamless roaming WiFi with fiber-optic backhaul.',
            'solution_id' => 'Mengimplementasikan WiFi roaming tanpa putus dengan jaringan serat optik.',
            'result_en' => '100% coverage with stable high-speed access across the property.',
            'result_id' => 'Cakupan 100% dengan akses berkecepatan tinggi yang stabil di seluruh properti.',
            'technologies' => ['Ubiquiti UniFi', 'Fiber Optic'],
        ],
        [
            'id' => 'corporate-office-denpasar',
            'image' => 'portfolio/office-denpasar.jpg',
            'gallery' => [],
            'before_after' => [],
            'title_en' => 'Corporate Office IT Infrastructure',
            'title_id' => 'Infrastruktur TI Kantor Korporat',
            'category_en' => 'Office',
            'category_id' => 'Kantor',
            'client_en' => 'Tech Startup, Denpasar',
            'client_id' => 'Startup Teknologi, Denpasar',
            'problem_en' => 'Messy cabling causing frequent network downtime and difficult maintenance.',
            'problem_id' => 'Kabel berantakan yang menyebabkan downtime jaringan sering terjadi dan sulit dirawat.',
            'solution_en' => 'Full structured cabling overhaul and professional server rack organization.',
            'solution_id' => 'Perombakan total kabel terstruktur dan organisasi rak server profesional.',
            'result_en' => 'Zero network interruptions and highly organized IT management.',
            'result_id' => 'Nol gangguan jaringan dan manajemen TI yang sangat terorganisir.',
            'technologies' => ['Cisco', 'Cat6A Cables'],
        ],
        [
            'id' => 'boutique-hotel-ubud',
            'image' => 'portfolio/hotel-ubud.jpg',
            'gallery' => [],
            'before_after' => [],
            'title_en' => 'Boutique Hotel WiFi Upgrade',
            'title_id' => 'Peningkatan WiFi Hotel Butik',
            'category_en' => 'Hotel',
            'category_id' => 'Hotel',
            'client_en' => 'Resort & Spa, Ubud',
            'client_id' => 'Resor & Spa, Ubud',
            'problem_en' => 'Guests complaining about slow internet during peak hours.',
            'problem_id' => 'Tamu mengeluh tentang internet lambat selama jam sibuk.',
            'solution_en' => 'Deployed enterprise-grade access points with bandwidth management.',
            'solution_id' => 'Mengerahkan access point tingkat enterprise dengan manajemen bandwidth.',
            'result_en' => 'Significantly improved guest satisfaction scores for internet connectivity.',
            'result_id' => 'Skor kepuasan tamu meningkat secara signifikan untuk konektivitas internet.',
            'technologies' => ['Ruijie Reyee', 'MikroTik'],
        ],
        [
            'id' => 'restaurant-pos-seminyak',
            'image' => 'portfolio/restaurant-seminyak.jpg',
            'gallery' => [],
            'before_after' => [],
            'title_en' => 'Restaurant POS Network',
            'title_id' => 'Jaringan POS Restoran',
            'category_en' => 'Restaurant',
            'category_id' => 'Restoran',
            'client_en' => 'Fine Dining, Seminyak',
            'client_id' => 'Fine Dining, Seminyak',
            'problem_en' => 'Point of Sale (POS) system losing connection to kitchen printers.',
            'problem_id' => 'Sistem Point of Sale (POS) sering kehilangan koneksi ke printer dapur.',
            'solution_en' => 'Isolated secure network dedicated exclusively for operational systems.',
            'solution_id' => 'Jaringan aman terisolasi khusus untuk sistem operasional.',
            'result_en' => 'Flawless order processing with 100% uptime during busy hours.',
            'result_id' => 'Pemrosesan pesanan tanpa cacat dengan 100% uptime selama jam sibuk.',
            'technologies' => ['TP-Link Omada', 'Grandstream'],
        ]
    ],

    'testimonials' => [
        [
            'name' => 'Budi Santoso',
            'role' => 'Operations Manager',
            'company' => 'The Grand Bali Resort',
            'quote_id' => 'Infrastruktur jaringan kami sering bermasalah sebelumnya. Sejak Jiwa Cyber Network mengambil alih, tidak pernah ada keluhan koneksi dari tamu hotel kami.',
            'quote_en' => 'Our network infrastructure was frequently problematic before. Since Jiwa Cyber Network took over, we have never had a connection complaint from our hotel guests.',
            'avatar' => 'team/avatar-1.jpg',
        ],
        [
            'name' => 'Sarah Johnson',
            'role' => 'Founder',
            'company' => 'Digital Hub Coworking',
            'quote_id' => 'Tim yang sangat profesional. Instalasi kabel sangat rapi dan jaringan WiFi mampu menangani ratusan pengguna tanpa masalah latensi.',
            'quote_en' => 'Extremely professional team. The cable installation is very neat and the WiFi network can handle hundreds of users without latency issues.',
            'avatar' => 'team/avatar-2.jpg',
        ],
        [
            'name' => 'Made Wijaya',
            'role' => 'IT Director',
            'company' => 'Bali Corporate Group',
            'quote_id' => 'Respon yang sangat cepat ketika kami membutuhkan bantuan. Mereka tidak hanya menginstal, tapi benar-benar memelihara ekosistem jaringan kami.',
            'quote_en' => 'Very fast response when we needed help. They do not just install, but truly maintain our entire network ecosystem.',
            'avatar' => 'team/avatar-3.jpg',
        ]
    ],

    'faq' => [
        [
            'q_id' => 'Berapa lama proses instalasi jaringan untuk kantor baru?',
            'q_en' => 'How long does the network installation process take for a new office?',
            'a_id' => 'Waktu instalasi bergantung pada ukuran dan kompleksitas lokasi. Umumnya, untuk kantor ukuran menengah (sekitar 20-50 karyawan), proses dari desain hingga pengujian selesai memakan waktu 3-7 hari kerja.',
            'a_en' => 'Installation time depends on the size and complexity of the location. Generally, for a medium-sized office (around 20-50 employees), the process from design to final testing takes 3-7 working days.',
        ],
        [
            'q_id' => 'Apakah Anda menyediakan layanan pemeliharaan rutin?',
            'q_en' => 'Do you provide routine maintenance services?',
            'a_id' => 'Ya, kami menyediakan kontrak pemeliharaan (SLA) secara bulanan maupun tahunan. Ini mencakup pemantauan jaringan proaktif, pembaruan firmware, dan kunjungan teknisi rutin.',
            'a_en' => 'Yes, we provide maintenance contracts (SLA) on a monthly or annual basis. This includes proactive network monitoring, firmware updates, and routine technician visits.',
        ],
        [
            'q_id' => 'Merek perangkat apa saja yang biasa Anda gunakan?',
            'q_en' => 'What equipment brands do you typically use?',
            'a_id' => 'Kami menggunakan perangkat berstandar enterprise yang telah teruji keandalannya, seperti Cisco, Ubiquiti UniFi, MikroTik, Ruijie, dan TP-Link Omada. Pemilihan merek akan disesuaikan dengan anggaran dan kebutuhan teknis Anda.',
            'a_en' => 'We use enterprise-standard equipment with proven reliability, such as Cisco, Ubiquiti UniFi, MikroTik, Ruijie, and TP-Link Omada. The choice of brand will be tailored to your budget and technical requirements.',
        ],
        [
            'q_id' => 'Apakah jaringan yang dipasang aman dari serangan siber?',
            'q_en' => 'Is the installed network safe from cyber attacks?',
            'a_id' => 'Keamanan adalah prioritas kami. Kami mengkonfigurasi firewall tingkat lanjut, pemisahan VLAN (antara staf, tamu, dan IoT), serta enkripsi WPA3 terbaru untuk memastikan data bisnis Anda aman dari ancaman eksternal.',
            'a_en' => 'Security is our priority. We configure advanced firewalls, VLAN segregation (between staff, guests, and IoT), and the latest WPA3 encryption to ensure your business data is safe from external threats.',
        ]
    ]
];
